import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import TopHeader from "../components/home/topHeaderNav/topHeader"
import HeaderDetails from '@/components/home/headerDetails/headerDetails'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" dir='rtl'>
      <body className={inter.className}>
        <TopHeader />
        <HeaderDetails />
      {children}
      </body>
    </html>
  )
}
