import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import TopHeader from "../components/home/topHeaderNav/topHeader"
import HeaderDetails from '@/components/home/headerDetails/headerDetails'
import ThirdNavBar from "@/components/home/thirdNavBar/ThirdNavBar";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" dir='rtl'>
      <head>
      <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css" /> 
      <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css" />
      </head>
      <body className={inter.className}>
        <TopHeader />
        <HeaderDetails />
        <ThirdNavBar />
      {children}
      </body>
    </html>
  )
}
